### ISSUE TITLE
[Feature]: `formulaUpdated` event

### ISSUE THREAD

**Issue by nomind2think** [handsontable/hyperformula#1408] opened 2024-04-18 02:15 UTC
### Description

when i insert/remove row, formula's relative address is change, but no valueUpdateEvent emit, how to listening this event?
```javascript
    const engine = HyperFormula.buildFromArray([
      ['1', '=SUM(A1:A2)'],
      ['1'],
    ])
    engine.on('valuesUpdated', (changes)=>{console.log(changes)})
    engine.addRows(engine, 0, [1, 1])
    //==SUM(A1:A3)
    console.log(engine.getCellFormula(adr('B1')))
```

### Demo

none

### HyperFormula version

2.7.0

### Your framework

vue

### Your environment

nodejs v18.17.1

**Comment by adrianszymanski89** [comment] 2024-04-18 13:16
Hi @CodeChaosConjurer 

Thank you for contacting us. I tried to recreate this behavior in this example, but there seems to be something wrong: https://stackblitz.com/edit/vitejs-vite-pjjrzz?file=index.html,main.js&terminal=dev. Can you please modify it so it matches your scenario?

**Comment by CodeChaosConjurer** [comment] 2024-04-19 02:39
> Hi @CodeChaosConjurer
> 
> Thank you for contacting us. I tried to recreate this behavior in this example, but there seems to be something wrong: https://stackblitz.com/edit/vitejs-vite-pjjrzz?file=index.html,main.js&terminal=dev. Can you please modify it so it matches your scenario?

https://stackblitz.com/edit/stackblitz-starters-2wmbyf?file=index.js i'm create a new stack. without vite,  just simple with nodejs. I want to listener formulas change event.

**Comment by adrianszymanski89** [comment] 2024-04-19 13:50
Hi @CodeChaosConjurer 

Unfortunately, this example still doesn't work for me. However, if you need a listener, did you try this method? https://hyperformula.handsontable.com/api/interfaces/listeners.html#values

**Comment by CodeChaosConjurer** [comment] 2024-04-22 02:37
> Hi @CodeChaosConjurer
> 
> Unfortunately, this example still doesn't work for me. However, if you need a listener, did you try this method? https://hyperformula.handsontable.com/api/interfaces/listeners.html#values

Hi, i'm fork your stackblitz, https://stackblitz.com/edit/vitejs-vite-yhajtz?file=index.html,main.js&terminal=dev will it work？
i try to use listening valuesUpdated event,but no event emit.`B1`'s raw formulas is `=SUM(A1:A2)`,after insert row is `=SUM(A1:A3)`,  The value is not updated but the formula is. But no event emit. 
I try to explain the steps to reproduce. 
The first step is to create a sheet with a formula as a relative reference address. 
The second step is to insert or delete a row that affects the expression of the formula but does not affect its value. This way there will be no valueUpdate event.

For example, the formula in cell `B1` is `=SUM(A1:A2)`. If you insert a row after the first row, the formula in `B1` becomes `=SUM(A1:A3)`, but the value of the inserted row is 0, which will not happen. Modify the value of `B1`, but the formula of `B1` has changed and I cannot receive any events.

**Comment by adrianszymanski89** [comment] 2024-04-22 14:39
Hi @CodeChaosConjurer 

I'm not sure if this example was updated. It throws an error that `adr` is not defined. Can you please check it again?

**Comment by CodeChaosConjurer** [comment] 2024-04-23 02:32
> Hi @CodeChaosConjurer
> 
> I'm not sure if this example was updated. It throws an error that `adr` is not defined. Can you please check it again?

sorry,try it again, i don't know how to run this program

**Comment by CodeChaosConjurer** [comment] 2024-04-23 02:38
> Hi @CodeChaosConjurer
> 
> I'm not sure if this example was updated. It throws an error that `adr` is not defined. Can you please check it again?

i 'm already fix it, plz try it again

**Comment by adrianszymanski89** [comment] 2024-04-23 13:39
Hi @CodeChaosConjurer 

Thank you. Now it works. We'll take a closer look at this, and I'll get back to you when I have more information.

**Comment by CodeChaosConjurer** [comment] 2024-04-24 06:50
> Hi @CodeChaosConjurer
> 
> Thank you. Now it works. We'll take a closer look at this, and I'll get back to you when I have more information.

Thank you~

**Comment by adrianszymanski89** [comment] 2024-04-24 12:55
Hi @CodeChaosConjurer 

We determined that, according to the documentation, this behavior is correct: https://hyperformula.handsontable.com/api/interfaces/listeners.html#valuesupdated

This hook is only fired on value change, not the formula, so it's the correct behavior in your case.

Here's an updated example showing that it works as expected: https://stackblitz.com/edit/vitejs-vite-ex3waj?file=index.html,main.js&terminal=dev

**Comment by CodeChaosConjurer** [comment] 2024-04-25 02:30
> Hi @CodeChaosConjurer
> 
> We determined that, according to the documentation, this behavior is correct: https://hyperformula.handsontable.com/api/interfaces/listeners.html#valuesupdated
> 
> This hook is only fired on value change, not the formula, so it's the correct behavior in your case.
> 
> Here's an updated example showing that it works as expected: https://stackblitz.com/edit/vitejs-vite-ex3waj?file=index.html,main.js&terminal=dev

ok,thanks,Is there any way for me to listen for formula change events?

**Comment by adrianszymanski89** [comment] 2024-04-25 12:56
Hi @nomind2think 

Currently, there's no such method available, but this is valuable feedback and that might be a good idea to add such method in the future.

**Comment by nomind2think** [comment] 2024-04-26 15:13
> Hi @nomind2think
> 
> Currently, there's no such method available, but this is valuable feedback and that might be a good idea to add such method in the future.

ok,thanks,I think this can be closed, what do you think?

**Comment by AMBudnik** [comment] 2024-04-29 07:45
Hi @nomind2think we can keep it open as a `feature`. I've just attached the exact label this this issue.

**Comment by sequba** [comment] 2024-07-10 11:05
Duplicate of https://github.com/handsontable/hyperformula/issues/1156

**Comment by sequba** [comment] 2024-07-10 11:05
Closing. Duplicate of https://github.com/handsontable/hyperformula/issues/1156.

**Closed by sequba** 2024-07-10 11:05 UTC
Labels: Feature, Impact: Low
