### ISSUE TITLE
[Bug]: Copying and pasting formulas pastes the value and not the formula

### ISSUE THREAD

**Issue by opike** [handsontable/hyperformula#1418] opened 2024-06-30 23:38 UTC
### Description

According to the documentation, relative cell references in formulas should be updated when copying and pasting:
https://hyperformula.handsontable.com/guide/cell-references.html#relative-references

However this is working for me - please seen screencast and demo link (you can type the formula "=A1" into cell E1 and then do a copy/paste).

### Video or screenshots

https://d.pr/i/wmueym

### Demo

https://codepen.io/opike99/pen/dyEBQWj

### HyperFormula version

2.7.0

### Your environment

Chrome 126.0.6478.127 MacOS 14.4.1

**Comment by adrianszymanski89** [comment] 2024-07-01 10:28
Hi @opike 

Thank you for contacting us. This operation will work if you use HyperFormula copy/paste methods: https://hyperformula.handsontable.com/guide/clipboard-operations.html#copy. The issue in your example is caused by the fact that Handsontable can't copy raw formulas, only the visual content of the cells.

**Comment by sequba** [comment] 2024-07-10 11:13
Closing this issue because it is not a HyperFormula bug.

The behavior of [Handsontable](https://github.com/handsontable/handsontable)'s copy-paste mechanism on formula cells is implemented in the [Handsontable](https://github.com/handsontable/handsontable) project.

**Closed by sequba** 2024-07-10 11:13 UTC
