### ISSUE TITLE
[Bug]: `simpleCellRangeToString` does not work with column ranges and row ranges

### ISSUE THREAD

**Issue by sandzone** [handsontable/hyperformula#1375] opened 2024-02-09 07:59 UTC
### Description

If the range has values with entire columns or rows, simpleCellRangeToString is not giving the correct answer.

### Video or screenshots

![image](https://github.com/handsontable/hyperformula/assets/2245672/f347b430-ef8c-4aa5-986d-577d30c08a42)

### Demo

none

### HyperFormula version

2.6.1

### Your environment

node v18.7

**Comment by adrianszymanski89** [comment] 2024-02-09 14:56
Hi @sandzone 

Thank you for contacting us. I wasn't able to get the same result as you. Can you please send us a code demo where the issue is replicable?

**Comment by sandzone** [comment] 2024-02-10 23:48
> Hi @sandzone
> 
> Thank you for contacting us. I wasn't able to get the same result as you. Can you please send us a code demo where the issue is replicable?

Thanks for the response. Here is a jsfiddle with the issue

https://jsfiddle.net/sandeep_muthangi/nsvqmbza/4/

![image](https://github.com/handsontable/hyperformula/assets/2245672/d4ef436b-8aee-466f-aec2-bc11d86d15a7)

**Comment by adrianszymanski89** [comment] 2024-02-12 10:48
Hi @sandzone 

Thank you for the example. I'm consulting our HyperFormula developer about it and should have more information by tomorrow. I'll keep you updated.

**Comment by sequba** [comment] 2024-02-13 19:08
Hi, @sandzone, thank you for reporting this issue.

Currently `simpleCellRangeToString` method does not work with column ranges and row ranges. We will discuss this issue with the HyperFormula team. We need to either describe this limitation in the API reference or make it work with all types of ranges.

**Comment by sequba** [comment] 2024-03-07 14:21
Estimation for making `simpleCellRangeToString` work with all types of ranges: 3 SP.

**Comment by AMBudnik** [comment] 2024-04-10 10:59
Hi @sandzone 

Thank you again for your contribution to make the better. I'm more than happy to announce that by the merge of https://github.com/handsontable/hyperformula/pull/1391 this issue made it to the 2.7.0 version, which was released today.

I'm closing this issue as done, but feel free to create a new one or write to us if you have any questions.

**Closed by AMBudnik** 2024-04-10 10:59 UTC
Labels: Bug, Impact: Low
