### ISSUE TITLE
VLOOKUP formula not returning the right value

### ISSUE THREAD

**Issue by impauloalves** [handsontable/hyperformula#1219] opened 2023-03-30 11:22 UTC
### Description

While comparing the VLOOKUP formula result from the hyperformula to Microsoft Excel, the results are different.

### Steps to reproduce

it('VLOOKUP formula', () => {
    const engine =HyperFormula.buildFromArray([
        ['d', 'B', 'C'],
        ['C', 'E', 'F'],
        ['a', 'a', 'a'],
        ['=VLOOKUP("C", A1:C3, 3, TRUE())'],
    ], hyperFormulaOptions);
    expect(engine.getCellValue({ col: 0, row: 3, sheet:0 })).toEqual('F');
});

The computed cell value is "a" instead of "F". I tried this with Excel and got the expected result.

* HyperFormula version: 2.3.1
* Browser Name and version: Chrome
* Operating System: MacOS

**Comment by adrianszymanski89** [comment] 2023-03-30 13:15
Closed as duplicate of: https://github.com/handsontable/hyperformula/issues/1220

**Closed by adrianszymanski89** 2023-03-30 13:15 UTC
Labels: Bug

**Comment by impauloalves** [comment] 2023-04-04 08:15
Hi @adrianszymanski89,
Are you sure this is a duplicate from #1220?
Thanks.

**Comment by adrianszymanski89** [comment] 2023-04-28 12:25
Hi @impauloalves

The reason for this problem is the same as in the mentioned issue. Let me know if the solution provided there solved the problem.
