### ISSUE TITLE
VLOOKUP not selecting the last value correctly

### ISSUE THREAD

**Issue by impauloalves** [handsontable/hyperformula#1220] opened 2023-03-30 11:31 UTC
Description
While comparing the VLOOKUP formula result from the hyperformula to Microsoft Excel, the results are different.

Steps to reproduce
it('VLOOKUP formula', () => {
    const engine =HyperFormula.buildFromArray([
        ['d', 'B', 'C', '=VLOOKUP("C", A1:C4, 3, TRUE())'],
        ['C', 'E', 'F'],
        ['a', 'a', 'a'],
    ], hyperFormulaOptions);
    expect(engine.getCellValue({ col: 3, row: 0, sheet:0 })).toEqual('a');
});

Expected: "a"
Received: {"address": "Sheet1!D1", "message": "Value not found.", "type": "NA", "value": "#N/A"}

The computed cell value is "#N/A" instead of "a". I tried this with Excel and got the expected result. It looks like the hyperformula tries to get the last cell from a cell that doesn't exist instead getting the last one available.

HyperFormula version: 2.3.1
Browser Name and version: Chrome
Operating System: MacOS

**Comment by adrianszymanski89** [comment] 2023-03-31 09:13
Hi @impauloalves 

I've checked the formula, and in this example, I get 'a' as a result: https://stackblitz.com/edit/js-izsbfs?file=index.html,index.js

Can you confirm if that's your expected output?

**Comment by adrianszymanski89** [comment] 2023-04-06 14:36
Hi @impauloalves 

Thank you for the new description. This time I was able to recreate the issue. However, it is not a bug. You use `Sort_Order=TRUE()` while your range isn't sorted.  In this case, the result will be as you presented.

**Comment by adrianszymanski89** [comment] 2023-04-19 08:52
Closed as it was determined it wasn't a bug.

**Closed by adrianszymanski89** 2023-04-19 08:52 UTC
Labels: Bug
