### ISSUE TITLE
Value of the formula cell is not computed.

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#548] opened 2020-10-19 18:43 UTC
```
VM18:37 ERROR Error: Value of the formula cell is not computed.
    at FormulaCellVertex.getCellValue (FormulaCellVertex.js:109)
    at AddressMapping.getCellValue (AddressMapping.js:120)
    at DependencyGraph.getCellValue (DependencyGraph.js:1245)
    at Interpreter.evaluateAstWithoutPostoprocessing (Interpreter.js:106)
    at Interpreter.evaluateAst (Interpreter.js:68)
    at Interpreter.evaluateAstWithoutPostoprocessing (Interpreter.js:126)
    at Interpreter.evaluateAst (Interpreter.js:68)
    at BooleanPlugin.evaluateAst (FunctionPlugin.js:209)
    at FunctionPlugin.js:111
    at Array.map (<anonymous>)
```

how can I debug this problem?

I get this error when setting the sheet content

**Comment by bardek8** [comment] 2020-10-19 19:25
Oh, actually this is an internal error that shouldn't appear, but apparently did.
We will greatly appreciate if you could provide us (here or via email) with a MWE for reproducing the error.
If this is not possible, we can try to start from your data (assuming you can share it), but this will take more time.

**Comment by doczoidberg** [comment] 2020-10-19 19:52
I sent a mail with 2 files.

**Comment by bardek8** [comment] 2020-10-23 14:07
@doczoidberg , we investigated the error you encountered. There is a bad and good news about it.

First, due to the issue #549 , we returned a wrong error in your example, which makes it more difficult to debug. Will be fixed soon.

The main problem you're encountering is that in the current design of the HyperFormula, we cannot return a reference to a cell from a function or `IF` statement, e.g. the following expression will fail `=COLUMN(IF(K25="nein",R20,S24))` as the `COLUMN` function expects an address, not the value of the cell.

Fortunately, in your case this seems that it suffices to replace all constructs of the form `COLUMN(IF(X,A,B))` to `IF(X,COLUMN(A),COLUMN(B))`, which is handled by HF and implements exactly the same logic.

We hope this will help!

**Comment by doczoidberg** [comment] 2020-10-23 14:09
great, thank you for four efforts!

**Comment by doczoidberg** [comment] 2020-11-02 13:08
I sent you another mail

**Comment by bardek8** [comment] 2020-11-04 22:39
PR #563 should fix the source of this problem.

**Comment by wojciechczerniak** [comment] 2020-12-09 09:01
Done in #563

**Closed by wojciechczerniak** 2020-12-09 09:01 UTC
Labels: Bug, Verified
