### ISSUE TITLE
save and load state

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#545] opened 2020-10-15 07:17 UTC
Because our `rebuildandcalculate()` call takes quite a time https://github.com/handsontable/hyperformula/issues/544 a saving and loading of the hyperformula state would be nice. 
Is the state much larger than the sheets content?

**Comment by bardek8** [comment] 2020-10-16 13:06
We don't think that this could be profitable to do. Essentially this would boil down to parsing again the sheet contents, unless you have very heavy computations involved. 
What you can also try is to set all sheet contents within a single batch execution, which should speed things up a bit.

**Comment by doczoidberg** [comment] 2020-10-16 13:10
unfortunately we have quite heavy computations. On slower machines one workbook takes around 1minute to load. (and we have multiple of them).

How can I batch?

**Comment by doczoidberg** [comment] 2020-10-16 13:53
what does HF do when setting the sheet content? What takes time? calculating the refs? Maybe I could save the dependency graph then?

**Comment by doczoidberg** [comment] 2020-10-16 14:03
please take a look here: https://lignaconfigurator.firebaseapp.com/?konfigurationstypid=TEST%20OLI
The console logs `sheet content set`. You can see there how long it takes to load the sheets. I think so over complicated are our sheets not btw.

**Comment by wojciechczerniak** [comment] 2021-03-04 08:22
I think this is a duplicate of #610 and should be handled exactly the same way. If 
Sorry for the late answer, I lost it somehow. If not related I will reopen.

**Closed by wojciechczerniak** 2021-03-04 08:22 UTC
Labels: Feature, Verified
