### ISSUE TITLE
[Bug]: Cannot set column order for sheets with empty, right-side columns

### ISSUE THREAD

**Issue by JohannCooper** [handsontable/hyperformula#1471] opened 2024-12-10 18:27 UTC
### Description

`HyperFormula.setColumnOrder` does not work when the right-side columns are empty.

Based on [this discussion](https://github.com/handsontable/hyperformula/issues/886), it seems like `HyperFormula.getSheetDimensions` is behaving as expected. What then is the recommend way to set the column order such that the empty column is between the two non-empty columns?

The only workaround I've found is to initialize my sheet using `""` instead of `null`.
```ts
const sheetName = "MySheet";
const engine = HyperFormula.buildFromSheets({
  [sheetName]: [["First", "=A1", ""]],
});
```

### Demo

https://codesandbox.io/p/sandbox/beautiful-hermann-pyz8z5

### HyperFormula version

2.7.1

### Your environment

Ubuntu 23.10

**Comment by adrianszymanski89** [comment] 2024-12-12 09:07
Hi @JohannCooper 

Thank you for contacting us. This is a correct behavior as this error is being thrown when:

> `columnMapping` does not define correct column permutation for some subset of columns of the given sheet

As mentioned in the documentation, this is because the `null` values aren't counted into the sheet width within the graph dependency.

**Comment by JohannCooper** [comment] 2024-12-12 18:19
Thanks for the reply @adrianszymanski89. I have two follow-ups.

1. Returning to my original question, is my solution the recommended way "to set the column order such that the empty column is moved between the two non-empty columns"?

> As mentioned in the documentation, this is because the null values aren't counted into the sheet width within the graph dependency.

2. Can you provide a link to the documentation where it describes how `null` values are expected to affect a sheet's width.

**Comment by JohannCooper** [comment] 2024-12-13 20:16
Thanks for clarifying @adrianszymanski89.

> as the `null` value isn't equal to or larger than 0 or an empty string, it isn't counted as a part of the sheet's width
> 

This seems to only be true if the `null` values appear on the right side of a sheet when the sheet is first initialized. If a sheet is initialized with `null` values on the left side or `null` values are moved to the right side after initialization, they are counted as part of the sheet’s width.

For example:

```ts
const engine = HyperFormula.buildFromSheets({
  MySheet: [[null, "First", "=B1"]],
});

// { width: 3, height: 1 }
console.log(engine.getSheetDimensions(0));
```

This exact case appears in [this unit test](https://github.com/handsontable/hyperformula/blob/76aaae5b5f5c02de1d1a365b7407d99789467650/test/cruds/set-column-order.spec.ts#L287).

What is unintuitive to me is that if you start with the case defined in the unit test and move the `null` value to the right side of its sheet, not only is it counted as part of the sheet’s width but it can also be moved using `setColumnOrder` unlike my original example.

```ts
const engine = HyperFormula.buildFromSheets({
  MySheet: [[null, "First", "Second"]],
});

// [ [ null, 'First', 'Second' ] ]
// { width: 3, height: 1 }
console.log(
  engine.getSheetSerialized(0),
  engine.getSheetDimensions(0)
);

// Move null value to right side of sheet
engine.setColumnOrder(0, [2, 0, 1]);

// [ [ 'First', 'Second' ] ]
// { width: 3, height: 1 }
console.log(
  engine.getSheetSerialized(0),
  engine.getSheetDimensions(0)
);

// Move null value from right side of sheet
// Same as original example but no error!
engine.setColumnOrder(0, [0, 2, 1]);

// [ [ 'First', null, 'Second' ] ]
// { width: 3, height: 1 }
console.log(
  engine.getSheetSerialized(0),
  engine.getSheetDimensions(0)
);
```

Demo: https://codesandbox.io/p/sandbox/hyperformula-set-column-order-bug-forked-fd9ljr?workspaceId=ws_DWrLGDSFaSWfpPsRDxaN3w

Sorry for the lengthy response. These results were unintuitive to me and I can't tell if this is a bug or expected behavior. I'd be happy to contribute to the documentation to explain this if I could get a better understanding of the expected behavior.

**Comment by adrianszymanski89** [comment] 2024-12-17 14:49
Hi @JohannCooper 

Thank you for your thorough investigation of this problem. At this point, I think our developer responsible for Hyperformula can better answer your question.

@sequba Can I please ask you to look at this issue? Thank you.

**Comment by sequba** [comment] 2024-12-18 08:10
Hi @JohannCooper,

Your observation about the `null` values is caused by the efficient memory handling in HyperFormula. For the rightmost columns and bottommost rows, the engine only puts them into the internal memory once it's necessary (e.g., they contain a non-empty value or they are referenced by some formula). Once a column/row is in the memory, it's not removed during the regular read/write operations performed on a sheet.

I can understand the confusion, as this mechanism causes sheet dimensions to change seemingly unpredictably.

> What then is the recommend way to set the column order such that the empty column is between the two non-empty columns?

As you already discovered, you can write a non-empty value (e.g., `""`) to a column to make sure it's kept in the memory, or you can set the order of the non-empty columns and then insert the empty one to the correct position:

```js
const sheetName = "MySheet";
const engine = HyperFormula.buildFromSheets({
  [sheetName]: [["First", "=A1"]],
});

const sheetId = engine.getSheetId(sheetName);

engine.setColumnOrder(sheetId, [0, 1]);
engine.addColumns(sheetId, [1, 1]);

console.log(engine.getSheetSerialized(sheetId));
```

**Comment by sequba** [comment] 2024-12-18 08:16
Personally, I wouldn't consider it a bug, but the documentation about [setColumnOrder](https://hyperformula.handsontable.com/api/classes/hyperformula.html#setcolumnorder) and [setRowOrder](https://hyperformula.handsontable.com/api/classes/hyperformula.html#setroworder) could be improved to make it clear, that the length of the permutation array must match the current sheet dimension.

**Comment by JohannCooper** [comment] 2024-12-19 20:24
@sequba

Thanks for explaining the reasoning behind the current API. Based your description, I agree that this isn't necessarily a bug.

In addition to your suggestion, it would be great to see this clarified in the documentation for [`getSheetDimensions`](https://hyperformula.handsontable.com/api/classes/hyperformula.html#sheets) as well. I'm sure others would benefit from better understanding how `null` values affect sheet width and height.

No further questions from my end! Thanks for all the thorough replies and for building an awesome package. Happy holidays! :sparkles:

**Comment by sequba** [comment] 2024-12-20 18:15
Ok. I'm closing this issue. The docs changes will be made in https://github.com/handsontable/hyperformula/pull/1476

**Closed by sequba** 2024-12-20 18:15 UTC
