### ISSUE TITLE
Vertex for address missing in AddressMapping when adding a row/col & then clearing the sheet

### ISSUE THREAD

**Issue by MartinDawson** [handsontable/hyperformula#855] opened 2021-11-06 15:26 UTC
Browser: Chrome
OS: Ubuntu 12.x
HF version: 1.3.0

Example with the error: https://codesandbox.io/s/gallant-jepsen-ix935?file=/src/index.js

Apologies for the large data set. I tried to figure out what is wrong but was unable to.

The bug only happens with `chooseAddressMappingPolicy: new AlwaysSparse()`. However I cannot change this in our code because we rely on `AlwaysSparse` (at least for now...)

If you change the `addRows` line to this -> `hf.addRows(0, [8, 1])` then hyperformula is NOT throwing any errors. So it's only before row 8 it throws.

Reproducible error code (probably depends on the data in `tableData`):
```js
import HyperFormula, { AlwaysSparse } from "hyperformula";
import { tableData } from "./data";

// Create an empty HyperFormula instance.
const hf = HyperFormula.buildFromSheets(tableData, {
  licenseKey: "gpl-v3",
  chooseAddressMappingPolicy: new AlwaysSparse()
});

hf.addRows(0, [0, 1]);

const sheetName = hf.getSheetName(0);

const sheetId = hf.getSheetId(sheetName);

hf.clearSheet(sheetId);
```

In my real code this bug happens after I add a row and undo on the spreadsheet.

We clear the current sheet and then set the hyperformula values again which results in the above error.

**Comment by sequba** [comment] 2022-04-26 11:12
I am sorry you experienced an issue with HyperFormula. Our team will investigate it and verify.

**Comment by sequba** [comment] 2022-10-25 10:49
Increasing impact since we received another similar bug report:

**Note: Using default `chooseAddressMappingPolicy`!**

```
Error: Vertex for address missing in AddressMapping
    at AddressMapping.fetchCell (AddressMapping.js?cb8a:36:1)
    at eval (DependencyGraph.js?3bb8:73:1)
    at Array.map (<anonymous>)
    at DependencyGraph.dependencyQueryVertices [as dependencyQuery] (DependencyGraph.js?3bb8:66:1)
    at Graph.removeDependencies (Graph.js?9e87:334:1)
    at Graph.removeNode (Graph.js?9e87:148:1)
    at DependencyGraph.removeVertexAndCleanupDependencies (DependencyGraph.js?3bb8:1176:1)
    at DependencyGraph.removeVertex (DependencyGraph.js?3bb8:1157:1)
    at DependencyGraph.removeSheet (DependencyGraph.js?3bb8:384:1)
    at Operations.removeSheet (Operations.js?0eba:153:1)
```

**Comment by sequba** [comment] 2022-11-10 14:08
Closing. We do not have enough information to address this issue. @MartinDawson please re-open it when you are able to provide a demo that reproduces the bug.

**Closed by sequba** 2022-11-10 14:08 UTC
Labels: Bug, Impact: High
