### ISSUE TITLE
#REF BUG not all dependencies are refresehd after adding a new sheet

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#493] opened 2020-08-14 08:00 UTC
I have a strange error on some cells. I get a `#REF!` Error when getting the cell value. Cell content is just `='Statik Tetra'!C44` 

`H169 DetailedCellError {value: "#REF!", type: "REF", message: ""}`

Resetting the content beforehand getting the cell value works:
 
```
var cellcontent = hfInstance.getCellFormula(this.hfInstance.simpleCellAddressFromString("H169", idxDT)); // H169 ='Statik Tetra'!C44
hfInstance.setCellContents(hfInstance.simpleCellAddressFromString("H169", idxDT), cellcontent);
hfInstance.getCellValue(this.hfInstance.simpleCellAddressFromString("H169", idxDT))); // works after reset
```

I have no idea why this could be.

**Comment by doczoidberg** [comment] 2020-08-18 07:43
I think this is a bug but I don't know why...

logging the formula and the value I get the value from the sheet direct but not via cross reference:

```
C44 =IF((F39+F40+F41)<3,24,VLOOKUP($V$46,$B$48:$U$120,2,FALSE))  
C44 16
H169 ='Statik Tetra'!C44
H169 DetailedCellError {value: "#REF!", type: "REF", message: ""}
```

**Comment by bardek8** [comment] 2020-08-18 13:03
Ok, we have an idea what might be the problem. When do you add the sheet `Statik Tetra`? 

The issue is that currently we do not refresh all the dependencies after adding a new sheet, for example:

```
const engine = HyperFormula.buildFromArray([["=FOO!A1"]])
expect(engine.getCellValue(adr("A1"))).toEqual(detailedError(ErrorType.REF))
engine.addSheet("FOO")
expect(engine.getCellValue(adr("A1"))).toEqual(detailedError(ErrorType.REF))
engine.setCellContents(adr("A1"), engine.getCellFormula(adr("A1")))
expect(engine.getCellValue(adr("A1"))).toEqual(null)
``` 
In other words, the reference `FOO!A1` suddenly becomes valid, but we do not notice that.
There are few possible workarounds for that:
- First add/rename all sheets and then fill them
- Read and write again the formula of the cell- this will properly update the dependencies
- Use `rebuildAndRecalculate()` method when you expect that many fields should be calculated, but you’re getting REFs.

We are planning to handle that properly in the future and now such mechanism is implemented only for named expressions.

Is this the problem you’re facing?

**Comment by doczoidberg** [comment] 2020-08-18 13:10
this is the problem. I have a helper function for now which rewrites the cell content if there is an #ref error when getting the value of a cell

**Comment by doczoidberg** [comment] 2020-09-09 08:10
if referenced cells have an ref error this is a problem for dependent cells. This issue should be labeled as bug, not question.

`rebuildAndRecalculate()` does not help
add/rename would only work if I do this in the right order?

**Comment by wojciechczerniak** [comment] 2020-09-11 12:07
Changed the label and milestone. The developer is already assigned. Thanks for the report

**Comment by bardek8** [comment] 2020-09-17 09:06
> `rebuildAndRecalculate()` does not help
> add/rename would only work if I do this in the right order?

Could you please explain this issue in more detail? Are the workarounds I provided above not working?
A few-line snippet of code would be the easiest for us to understand :)

**Comment by doczoidberg** [comment] 2020-09-21 10:50
I setup a test project: https://github.com/doczoidberg/hftests2

when executing `rebuildAndRecalculate()` I get many #value errors.
When not calling it I get many results but also many ref errors.

**Comment by doczoidberg** [comment] 2020-09-22 14:09
This is a very basic bug. For most people which use cross sheet references this library is unusable at this state.

Please fix these basic problems first before adding new features.

A workaround is nearly impossible for me. I work for days now at workarounds for this problem and always get new problems.

**Comment by bardek8** [comment] 2020-09-22 15:56
Thank you for providing us with the example, we're trying to investigate that. For the future, it will be slightly easier for us to work with *smaller* examples :)

> When not calling it I get many results but also many ref errors.

I just wanted to make sure, is this intended that there are >2500 #REF errors already present in the input data? For example `"=IF(#REF!=Auswahl!BU4,1,4)"` and `IF(DeltaTetra!#REF!=Auswahl!$CS$5`

**Comment by doczoidberg** [comment] 2020-09-22 18:05
not sure how you get the >2500 errors. Just take a look at the console. e.g. https://github.com/doczoidberg/hftests2/blob/7a0919fb2b9ee9a0b2c39c5aa0e3138fd2dcf9a4/src/app/app.component.ts#L78

the excel doesn't have those errors

**Comment by bardek8** [comment] 2020-09-22 19:28
I found those errors in the [the json file](https://github.com/doczoidberg/hftests2/blob/7a0919fb2b9ee9a0b2c39c5aa0e3138fd2dcf9a4/src/assets/_deltatetraneu.json) from your repository with the whole spreadsheet.
Could you maybe also provide us with the excel file? This would make it easier to understand the data.

**Comment by doczoidberg** [comment] 2020-09-22 19:33
the #ref errors in the json doesn't matter. those cells are not needed. can you give me your mail address? mine is info at seoaachen.de

**Comment by bardek8** [comment] 2020-09-22 19:49
Sure! I've just sent you an email.
Ok, this will make things easier if we are sure that we don't touch the cells with #ref on input. We suspected that there might be a problem with coercion of errors.

**Comment by bardek8** [comment] 2020-09-25 12:19
@doczoidberg , the above PR hopefully will address all the issues you found. Interestingly, it seems that cross-sheet references were working correctly all the time :)

**Comment by doczoidberg** [comment] 2020-09-25 14:26
that's great news! I'll check that

**Comment by doczoidberg** [comment] 2020-09-29 08:48
I compiled and installed https://github.com/handsontable/hyperformula/tree/jk/lookup-reference-functions.
But unfortunately I still get `#REF` errors.

e.g. in my example code on:
```

hfInstance.getCellValue({sheet: 0, col: 5, row: 2}); // works
hfInstance.getCellValue({sheet: 0, col: 5, row: 3}); // #ref
hfInstance.getCellValue({sheet: 0, col: 5, row: 4}); // works
hfInstance.getCellValue({sheet: 0, col: 5, row: 5}); // #ref
```

**Comment by bardek8** [comment] 2020-09-29 21:45
@doczoidberg , the branch you linked didn't contain all the fixes that we did recently. Now `develop` is up-to-date - could you please try again with it?
We run HF on the whole file from your repository and it worked (well, up REFs in the input data).

**Comment by doczoidberg** [comment] 2020-09-29 21:52
@bardek8 
I allready tried the develop branch with the latest fixes but get the same errors.

**Comment by bardek8** [comment] 2020-09-30 07:43
Just to double check - did you use the most up-to-date `develop` branch? In particular, the last PR with fixes was merged after your question (late afternoon yesterday).

If so, could you please update your repository hftests with the example how you are using HF? Or send me via email if you prefer. It will be much easier for us to investigate the problem.

**Comment by doczoidberg** [comment] 2020-09-30 08:57
@bardek8 I checked again. I updated my test app. Please take a look:
https://github.com/doczoidberg/hftests2/blob/17af2d753cd007c86bd69cd404d727771c733e70/src/app/app.component.ts#L49

**Comment by bardek8** [comment] 2020-09-30 12:55
But you are not using `RebuildAndRecalculate` :)

Maybe I didn't make it precise enough, but my [above comment](https://github.com/handsontable/hyperformula/issues/493#issuecomment-675465396) is still valid and you still need one of these workarounds.
We fixed different problems that affected your example and made it difficult to understand the issues.

**Comment by doczoidberg** [comment] 2020-09-30 13:02
ok, seems to work with `RebuildAndRecalculate`, but I have also to recall
```
    hfInstance.addNamedExpression('TRUE', '=TRUE()')
    hfInstance.addNamedExpression('FALSE', '=FALSE()')
```
again after the rebuild!

**Comment by bardek8** [comment] 2020-09-30 15:59
Great to hear that! 

As for the named expressions, we also noticed this problem and already addressed it int #527 .
Could you please confirm that this is not working for you? If so, maybe you can reopen this issue with a MWE that would allow us to reproduce?

**Comment by doczoidberg** [comment] 2020-09-30 16:06
I can't reopen the issue but commented on it:
https://github.com/handsontable/hyperformula/issues/527#issuecomment-701488188

**Comment by bardek8** [comment] 2020-10-08 16:26
@doczoidberg , what is the status here?

**Comment by doczoidberg** [comment] 2020-10-08 16:27
I think this issue can be closed

**Closed** 2020-10-08 16:27 UTC
Labels: Bug, Evaluator, Verified
