### ISSUE TITLE
Calculation of cell references as in excel

### ISSUE THREAD

**Issue by doczoidberg** [handsontable/hyperformula#887] opened 2022-01-20 21:35 UTC
Hi,
is it possible to do an automatic cell reference calculation or calculation as in excel when dropping down the + at the down right (in combination with handsontable)?
 
![image](https://user-images.githubusercontent.com/1972209/150425782-5fecc586-1ea4-4dd2-a549-d7a38ed719bc.png)

**Comment by bardek8** [comment] 2022-01-21 00:23
If I'm not mistaken, this might be achieved in HyperFormula in two ways:
a) by copying the formula to all the cells below,
b) by filling the range using the `getFillRangeData` method.

I know this might be counter-intuitive at first glance, but both the methods work as we operate on relative addresses underneath :)

**Comment by doczoidberg** [comment] 2022-01-21 12:51
@bardek8 thank you. It seems to work with `getFillRangeData` with Cell references.

Does this also work with e.g. numbers?
1,2,3 =>
1,2,3,4,5
?
It results to 1,2,3,1,2 for me. 
If HF has no implementation for this, can you name me approach what can I do to implement such a logic?

**Comment by bardek8** [comment] 2022-01-21 15:48
Great to hear that it worked!

No, currently HF has no mechanism for detecting the integer sequences and 1,2,3,1,2 is the intended behavior for now.
We did try a bit to understand the logic here, but it turns out to be very complicated. For example we can have:
```
1,3,2...
"day 1", "day 2", ...
"Monday", "Tuesday", ...
"1 a 1", "2 a 2", ...
```

For the arithmetic progressions from your example, in order to obtain the new element of the sequence you can add the difference between last two numbers to the last number.

**Comment by doczoidberg** [comment] 2022-01-21 15:57
seems to be some string manipulation and excel's `TREND` function (which is not supported in hf)

**Comment by warpech** [comment] 2022-02-10 10:08
What works: The problem in topic, as it is already used in Handsontable (see example: https://jsfiddle.net/t69xfk0z/, see source: https://github.com/handsontable/handsontable/blob/cf14362f963befe2d7ecbbda733e721a300b4bb2/handsontable/src/plugins/formulas/formulas.js#L607)

What doesn't work:
1. there is no guide in the docs about `getFillRangeData`, only a short API reference and a mention in two blog posts: https://handsontable.com/blog/articles/2021/10/whats-new-in-hyperformula-1.3.0, https://handsontable.com/blog/articles/2021/7/hyperformula-1-0-0-has-landed. A guide is needed.
2. a potential new feature about making the sequence detection smarter.

**Comment by sequba** [comment] 2022-02-10 16:24
@warpech I created issues to track these 2 tasks:
1. #902
2. #903

Closing this one

**Closed by sequba** 2022-02-10 16:24 UTC
Labels: Question

**Comment by warpech** [comment] 2022-02-14 21:07
@doczoidberg we will follow this idea for HyperFormula in the new issue #903.

Please keep in mind that HyperFormula is a library. If your intention is that this would be a nice feature in Handsontable formula plugin, I would be grateful for writing a feature request in Discussions: https://github.com/handsontable/handsontable/discussions/categories/ideas

On a side note, developers who integrate Handsontable in their apps can use `beforeAutofill` to implement custom autofill behaviour: https://github.com/handsontable/handsontable/issues/133
