### ISSUE TITLE
Percent/Currency value types are incorrect

### ISSUE THREAD

**Issue by MartinDawson** [handsontable/hyperformula#686] opened 2021-06-05 09:29 UTC
Actual:

`1%` & `1$` results in a valueType of `NUMBER` and a valueDetailedType of NUMBER_RAW.

Expected:

`1%` & `1$` should result in a valueType of `NUMBER_PERCENT` and `NUMBER_CURRENCY`.

Because the format is wrong if you then try and do getCellValue on it it will produce a NaN value. This means I cannot use `getAllSheetsSerializedValues() `and use that to build another sheet because it produces NaN results.

### Steps to reproduce

Simple follow this steps here: https://handsontable.github.io/hyperformula/api/classes/hyperformula.html#getcellvaluedetailedtype

* HyperFormula version: 0.6.0
* Browser Name and version: Chrome latest
* Operating System: Windows 10

Here's my testing showing the bad results: 
![image](https://user-images.githubusercontent.com/15030491/120886949-54c1be80-c5e8-11eb-92b7-8ee890bb0ae5.png)

**Comment by izulin** [comment] 2021-06-06 10:09
I am unable to reproduce this behaviour. Following code passes all tests for me:
```
    const engine = HyperFormula.buildFromArray([['1$', '1%']])
    const a1 = {sheet: 0, col: 0, row: 0}
    expect(engine.getCellValueType(a1)).toEqual('NUMBER')
    expect(engine.getCellValueDetailedType(a1)).toEqual('NUMBER_CURRENCY')
    expect(engine.getCellValueFormat(a1)).toEqual('$')
    expect(engine.getCellValue(a1)).toEqual(1)
    const b1 = {sheet: 0, col: 1, row: 0}
    expect(engine.getCellValueType(b1)).toEqual('NUMBER')
    expect(engine.getCellValueDetailedType(b1)).toEqual('NUMBER_PERCENT')
    expect(engine.getCellValueFormat(b1)).toEqual(undefined)
    expect(engine.getCellValue(b1)).toEqual(0.01)
```

**Comment by MartinDawson** [comment] 2021-06-06 10:11
@izulin thanks for replying/investigating so fast. That's strange, I'll look into it and see what's happening and get back here soon

**Comment by izulin** [comment] 2021-06-06 10:30
@MartinDawson two random things to check:
- is the '$' and '%' sign actual dollar and percent (there might be some unicode weirdness of other characters looking similarly)

- what are the engine options? you can get them with `.getConfig()` method

**Comment by MartinDawson** [comment] 2021-06-06 10:33
I’ll check when I’m back home later exact my but the config I was using was
just the default, ie no config so should be fine

I’ll check Unicode chars are correct too, good idea

Thanks

**Comment by MartinDawson** [comment] 2021-06-07 17:44
Haven't had time to test it yet but my node version is: 12.20.1.

I wonder if it's because of that as per the first line: https://handsontable.github.io/hyperformula/guide/known-limitations.html

**Comment by izulin** [comment] 2021-06-07 19:18
Trying to run the code from those unit tests might also help us debug it:
https://github.com/handsontable/hyperformula/blob/43071aa2a822ddcea04a7b1016fa3e8dda78e751/test/CellContentParser.spec.ts#L136
https://github.com/handsontable/hyperformula/blob/43071aa2a822ddcea04a7b1016fa3e8dda78e751/test/CellContentParser.spec.ts#L154

**Comment by MartinDawson** [comment] 2021-06-07 19:20
Thanks for the link, I was actually looking for that :)

I’ll run those and see what I did wrong

**Comment by MartinDawson** [comment] 2021-06-08 17:37
@izulin I tried running the unit tests and it worked fine for me on 14.x

However I tried in code sandbox and it doesn't work.

I think the issue is failing in js browser environments and working in nodejs.

See here please: https://codesandbox.io/s/quizzical-cache-6gbj8?file=/src/index.js

And observe the console.

**Comment by MartinDawson** [comment] 2021-06-08 17:39
Here's my config:

```

Config {accentSensitive: false, caseSensitive: false, caseFirst: "lower", ignorePunctuation: false, chooseAddressMappingPolicy: AlwaysDense…}
accentSensitive: false
caseSensitive: false
caseFirst: "lower"
ignorePunctuation: false
chooseAddressMappingPolicy: AlwaysDense
dateFormats: Array(2)
timeFormats: Array(2)
functionArgSeparator: ","
decimalSeparator: "."
language: "enGB"
licenseKey: ""
thousandSeparator: ""
localeLang: "en"
functionPlugins: Array(0)
gpujs: undefined
gpuMode: "gpu"
smartRounding: true
matrixDetection: true
matrixDetectionThreshold: 100
evaluateNullToZero: false
nullYear: 30
precisionRounding: 14
precisionEpsilon: 1e-13
useColumnIndex: false
useStats: false
binarySearchThreshold: 20
parseDateTime: ƒ defaultParseToDateTime() {}
stringifyDateTime: ƒ defaultStringifyDateTime() {}
stringifyDuration: ƒ defaultStringifyDuration() {}
translationPackage: TranslationPackage
errorMapping: Object
nullDate: Object
leapYear1900: false
undoLimit: 20
useRegularExpressions: false
useWildcards: true
matchWholeCell: true
maxRows: 40000
maxColumns: 18278
currencySymbol: Array(1)
<constructor>: "Config"
```

**Comment by izulin** [comment] 2021-06-09 15:52
The problem lies in the code relating to matrix detection, which is being phased out anyway.
Until new release comes, please do use `matrixDetection: false` option in the config. (e.g. `HyperFormula.buildFromArray([["1%"]], { matrixDetection: false })`)


In fact, this problem is not related to specific browser setting (which I am truly grateful for :) )
and can be replicated locally by running     
```
const x = HyperFormula.buildFromArray([['1%']], {matrixDetection: true})
expect(x.getCellValue(adr('A1'))).toEqual(0.01)  // result is NaN
```
on e.g. `0.6.2` release


cc: @wojciechczerniak

**Comment by izulin** [comment] 2021-06-09 15:53
(or you can switch to `develop` branch if it is possible)

**Comment by MartinDawson** [comment] 2021-06-09 15:55
@izulin Turning off matrixDetection works so I'll do that for now.

Thank you

**Comment by izulin** [comment] 2021-06-09 15:56
Happy to help!

**Comment by izulin** [comment] 2021-06-09 16:17
(This should be close when we release new version.)

**Comment by wojciechczerniak** [comment] 2021-06-17 12:39
Closing as done

**Closed by wojciechczerniak** 2021-06-17 12:39 UTC
Labels: Bug
