### ISSUE TITLE
The github actions workflow for publishing the docs crashed for 1.3.1.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/hyperformula#884] opened 2022-01-11 11:00 UTC
### Description
The GHA workflow responsible for building and publishing the documentation crashed on `npm ci` after publishing `1.3.1`: https://github.com/handsontable/hyperformula/runs/4773934020?check_suite_focus=true

It looks to me like it might be caused by the `gl` package being built on the fly and having some internal issues. 
The `ci` calls were successful for other workflows, which leads me to a conclusion, that the problem might be caused by using a different Node version for the publishing workflow (others use Node@14 and Node@15, the publishing one doesn't have a fixed Node version).

I think it'd be a good idea to check if setting the same (tested) version of Node for all workflows would fix the issue.

### Steps to reproduce
1. See the log at https://github.com/handsontable/hyperformula/runs/4773934020?check_suite_focus=true

**Comment by warpech** [comment] 2022-02-10 09:49
Adding this to the scope of the next release. If we fail to fix it easily, then we can postpone it.

**Comment by sequba** [comment] 2022-03-23 15:32
I could not reproduce this issue on develop. It might have been fixed earlier by something else or it happens only on master. We must make sure that the workflow completes after the release.

**Comment by sequba** [comment] 2022-04-15 11:19
Fixed by #946

**Closed by sequba** 2022-04-15 11:19 UTC
Labels: Bug, Docs
