### ISSUE TITLE
The demos in the documentation throw visible errors while checking their functionality on Chrome

### ISSUE THREAD

**Issue by aninde** [handsontable/hyperformula#1014] opened 2022-06-14 13:00 UTC
### Description

Each of the demos in the documentation throw an error in the Codesandbox placed in the documentation.
In my environment, these errors can be seen only in the incognito mode.

Issue is related only to Chrome Browser. Checked on `102.0.5005.115 (Official Build) (x86_64)` &  Beta `103.0.5060.42 (Official Build) beta (x86_64)`
```
Error during service worker registration: 
Error {}
```
![Screenshot 2022-06-14 at 14 47 50](https://user-images.githubusercontent.com/30186818/173582735-c111dde3-250c-4a9e-b48d-72c1e3facfc6.png)

Errors do not occur when checking the demos locally, without documentation,
nor when demos are opened separately in Codesandbox without documentation eg. https://codesandbox.io/s/github/handsontable/hyperformula-demos/tree/2.0.x/vanillajs-demo?from-embed

#### Browser's console
 with vanilla demos: 

```
index.js:27 
Error during service worker registration: DOMException: Failed to register a ServiceWorker for scope (‘https://c8l92o.csb.app/’) with script (‘https://c8l92o.csb.app/sandbox-service-worker.js’): The user denied permission to use Service Worker.
i.<computed>@index.js:27(anonymous)@sandbox.7e9b6d925.js:443Promise.catch (async)s@sandbox.7e9b6d925.js:442t.default@sandbox.7e9b6d925.js:377(anonymous)@sandbox.7e9b6d925.js:10335Promise.then (async)./src/sandbox/index.ts@sandbox.7e9b6d925.js:10335i@sandbox.7e9b6d925.js:857@sandbox.7e9b6d925.js:10347i@sandbox.7e9b6d925.js:85n@sandbox.7e9b6d925.js:46(anonymous)@sandbox.7e9b6d925.js:222(anonymous)@sandbox.7e9b6d925.js:1
```

#### Integration with React
```
index.js:27 Error during service worker registration: DOMException: Failed to register a ServiceWorker for scope ('https://ryuge9.csb.app/') with script ('https://ryuge9.csb.app/sandbox-service-worker.js'): The user denied permission to use Service Worker.
```

#### Integration with Vue
```
index.js:27 Error during service worker registration: DOMException: Failed to register a ServiceWorker for scope ('https://thzm13.csb.app/') with script ('https://thzm13.csb.app/sandbox-service-worker.js'): The user denied permission to use Service Worker.
```
#### Integration with Angular
```
index.js:27 Error during service worker registration: DOMException: Failed to register a ServiceWorker for scope ('https://y17r1y.csb.app/') with script ('https://y17r1y.csb.app/sandbox-service-worker.js'): The user denied permission to use Service Worker.
```

### Example:
https://handsontable.github.io/hyperformula/guide/demo.html
https://handsontable.github.io/hyperformula/guide/basic-usage.html#demo
https://handsontable.github.io/hyperformula/guide/advanced-usage.html#demo
https://handsontable.github.io/hyperformula/guide/integration-with-react.html#demo
https://handsontable.github.io/hyperformula/guide/integration-with-vue.html#demo
https://handsontable.github.io/hyperformula/guide/integration-with-angular.html#demo
https://handsontable.github.io/hyperformula/guide/basic-operations.html#demo
https://handsontable.github.io/hyperformula/guide/batch-operations.html#demo
https://handsontable.github.io/hyperformula/guide/clipboard-operations.html#demo
https://handsontable.github.io/hyperformula/guide/undo-redo.html#demo
https://handsontable.github.io/hyperformula/guide/sorting-data.html#data-sorting-demo
https://handsontable.github.io/hyperformula/guide/named-expressions.html#demo
https://handsontable.github.io/hyperformula/guide/localizing-functions.html#demo
https://handsontable.github.io/hyperformula/guide/date-and-time-handling.html#demo

![image](https://user-images.githubusercontent.com/2480086/175030984-231d0231-23bd-48c3-8918-13f74bc240da.png)
![image](https://user-images.githubusercontent.com/2480086/175031030-9e67742d-1bdf-4131-b3eb-3c74ca7bdf87.png)

### Type of issue

- [ ] Missing documentation
- [x] Error in the documentation
- [ ] Request for a demo
- [ ] Request for a tutorial, guide etc.
- [ ] Other issues, suggestions or ideas

**Comment by sequba** [comment] 2022-06-21 14:05
@warpech @aninde I investigated this issue. It's caused by blocking third-party cookies so - depending on your browser settings - it may happen only in incognito mode, always or never. I don't think we can do anything about it.

![image](https://user-images.githubusercontent.com/2480086/174818190-59f9301c-db74-4164-94d4-857a1fa93c17.png)

**Comment by warpech** [comment] 2022-06-23 07:50
@sequba for reference, can you please add a full page screenshot of how the error looks like?

After that, we should close the issue as a "won't fix".

**Comment by sequba** [comment] 2022-06-23 08:02
Full-page screenshot:
![image](https://user-images.githubusercontent.com/2480086/175248008-79264194-cbe3-4c70-a6ec-83adfbf58178.png)

**Comment by sequba** [comment] 2022-06-23 08:06
Closing as the issue is caused by third-party cookies being blocked in the browser.

**Closed by sequba** 2022-06-23 08:06 UTC
Labels: Bug, Docs, Wontfix, Impact: Medium
